### ISSUE TITLE
Value of type String has no member 'safeguard'

### ISSUE THREAD

**Issue by sirvon** [namolnad/safeguard#8]
```
            guard let userID = recordID?.recordName.safeguard() else {
                print("Unable to get unique user ID")
                return
            }

I get the error....
```
Value of type String has no member 'safeguard'

what gives?

**Comment by namolnad** [comment]
Hey @sirvon, thanks for reaching out about this. You're seeing this happen because `safeguard()` exists only on `Optional` types, whereas recordName is a `String` (not an `Optional<String>`). 

At the moment Safeguard doesn't support single-call use w/ `Optional` chaining (like this, for example: `guard let blah = optional1?.optional2?.optional3.safeguard()`), but it's something we're thinking about and looking into for future releases.

In the meantime, there are a couple of different ways you could approach this, depending on what works best for your use case:
Option 1: 
```swift
guard let userID = recordID.safeguard()?.recordName else {
  print("Unable to get unique user ID")
  return
}
```
Option 2:
```swift
guard let userID = recordID.safeguard() else {
  print("Unable to get unique user ID")
  return
}
// assign to something else here 
// let userIDString = userID.recordName 
//    or 
// access via dot notation when needed
// print(userID.recordName)
```

Hopefully that helps!
